export const comentariosConCalificacion = [
  { comentario: "Excelente servicio", calificacion: 5 },
  { comentario: "Buen trato", calificacion: 4 },
  { comentario: "Podría mejorar la rapidez", calificacion: 3 },
  { comentario: "Muy insatisfecho", calificacion: 1 },
  { comentario: "Muy recomendado", calificacion: 5 },
  { comentario: "Regular", calificacion: 2 },
  { comentario: "Satisfecho con el producto", calificacion: 4 },
  { comentario: "Atención al cliente amable", calificacion: 5 },
  { comentario: "Mal servicio", calificacion: 1 },
  { comentario: "Cumple con las expectativas", calificacion: 4 },
  { comentario: "No lo recomendaría", calificacion: 2 },
  { comentario: "Rápido y eficiente", calificacion: 5 },
  { comentario: "Deficiente", calificacion: 1 },
  { comentario: "Buena relación calidad-precio", calificacion: 4 },
  { comentario: "Mejorable", calificacion: 2 },
  { comentario: "Fantástico", calificacion: 5 },
  { comentario: "No me gustó", calificacion: 1 },
  { comentario: "Aceptable", calificacion: 1 },
  { comentario: "Increíble", calificacion: 5 },
  { comentario: "No volvería a comprar", calificacion: 2 },
  { comentario: "Hola", calificacion: 5 },
];
